main_root_dir: artifacts

DataIngestion:
  root_dir: artifacts/data_ingestion
  source_url: 'stacked-summaries/stacked-samsum-1024'
  train_csv: artifacts/data_ingestion/train.csv
  test_csv: artifacts/data_ingestion/test.csv
  validation_csv: artifacts/data_ingestion/validation.csv
